In [1]:
import pandas as pd

In [3]:
df=pd.read_csv('agora.csv')

In [4]:
df

    Marketing Spend  Administration  Transport     Area     Profit
0         114523.61       136897.80  471784.10    Dhaka  192261.83
1         162597.70       151377.59  443898.53      Ctg  191792.06
2         153441.51       101145.55  407934.54  Rangpur  191050.39
3         144372.41       118671.85  383199.62    Dhaka  182901.99
4         142107.34        91391.77  366168.42  Rangpur  166187.94
5         131876.90        99814.71  362861.36    Dhaka  156991.12
6         134615.46       147198.87  127716.82      Ctg  156122.51
7         130298.13       145530.06  323876.68  Rangpur  155752.60
8         120542.52       148718.95  311613.29    Dhaka  152211.77
9         123334.88       108679.17  304981.62      Ctg  149759.96
10        101913.08       110594.11  229160.95  Rangpur  146121.95
11        100671.96        91790.61  249744.55      Ctg  144259.40
12         93863.75       127320.38  249839.44  Rangpur  141585.52
13         91992.39       135495.07  252664.93      Ctg  134307.35
14        119943.24       156547.42  256512.92  Rangpur  132602.65
15        165349.20       122616.84  261776.23    Dhaka  129917.04
16         78013.11       121597.55  264346.06      Ctg  126992.93
17         94657.16       145077.58  282574.31    Dhaka  125370.37
18         91749.16       114175.79  294919.57  Rangpur  124266.90
19         86419.70       153514.11        NaN    Dhaka  122776.86
20         76253.86       113867.30  298664.47      Ctg  118474.03
21         78389.47       153773.43  299737.29    Dhaka  111313.02
22         73994.56       122782.75  303319.26  Rangpur  110352.25
23         67532.53       105751.03  304768.73  Rangpur  108733.99
24         77044.01        99281.34  140574.81    Dhaka  108552.04
25         64664.71       139553.16  137962.62      Ctg  107404.34
26         75328.87       144135.98  134050.07  Rangpur  105733.54
27         72107.60       127864.55  353183.81    Dhaka  105008.31
28         66051.52       182645.56  118148.20  Rangpur  103282.38
29         65605.48       153032.06  107138.38    Dhaka  101004.64
30         61994.48       115641.28   91131.24  Rangpur   99937.59
31         61136.38       152701.92   88218.23    Dhaka   97483.56
32         63408.86       129219.61   46085.25      Ctg   97427.84
33         55493.95       103057.49  214634.81  Rangpur   96778.92
34         46426.07       157693.92  210797.67      Ctg   96712.80
35         46014.02        85047.44  205517.64    Dhaka   96479.51
36         28663.76       127056.21  201126.82  Rangpur   90708.19
37         44069.95        51283.14  197029.42      Ctg   89949.14
38         20229.59        65947.93  185265.10    Dhaka   81229.06
39         38558.51        82982.09  174999.30      Ctg   81005.76
40         28754.33       118546.05  172795.67      Ctg   78239.91
41         27892.92        84710.77  164470.71  Rangpur   77798.83
42         23640.93        96189.63  148001.11      Ctg   71498.49
43         15505.73       127382.30   35534.17    Dhaka   69758.98
44         22177.74       154806.14   28334.72      Ctg   65200.33
45          1000.23       124153.04    1903.93    Dhaka   64926.08
46          1315.46       115816.21  297114.46  Rangpur   49490.75
47             0.00       135426.92       0.00      Ctg   42559.73
48           542.05        51743.15       0.00    Dhaka   35673.41
49             0.00       116983.80   45173.06      Ctg   14681.40

In [5]:
from sklearn.preprocessing import MinMaxScaler

In [6]:
scaler=MinMaxScaler()

In [8]:
marketing_scale_fit=scaler.fit(df[['Marketing Spend']])

In [9]:
marketing_scale_fit

MinMaxScaler()

In [10]:
df['Marketing Spend']=scaler.transform(df[['Marketing Spend']])

In [11]:
df

    Marketing Spend  Administration  Transport     Area     Profit
0          0.692617       136897.80  471784.10    Dhaka  192261.83
1          0.983359       151377.59  443898.53      Ctg  191792.06
2          0.927985       101145.55  407934.54  Rangpur  191050.39
3          0.873136       118671.85  383199.62    Dhaka  182901.99
4          0.859438        91391.77  366168.42  Rangpur  166187.94
5          0.797566        99814.71  362861.36    Dhaka  156991.12
6          0.814128       147198.87  127716.82      Ctg  156122.51
7          0.788018       145530.06  323876.68  Rangpur  155752.60
8          0.729018       148718.95  311613.29    Dhaka  152211.77
9          0.745906       108679.17  304981.62      Ctg  149759.96
10         0.616351       110594.11  229160.95  Rangpur  146121.95
11         0.608845        91790.61  249744.55      Ctg  144259.40
12         0.567670       127320.38  249839.44  Rangpur  141585.52
13         0.556352       135495.07  252664.93      Ctg  134307.35
14         0.725394       156547.42  256512.92  Rangpur  132602.65
15         1.000000       122616.84  261776.23    Dhaka  129917.04
16         0.471808       121597.55  264346.06      Ctg  126992.93
17         0.572468       145077.58  282574.31    Dhaka  125370.37
18         0.554881       114175.79  294919.57  Rangpur  124266.90
19         0.522650       153514.11        NaN    Dhaka  122776.86
20         0.461169       113867.30  298664.47      Ctg  118474.03
21         0.474084       153773.43  299737.29    Dhaka  111313.02
22         0.447505       122782.75  303319.26  Rangpur  110352.25
23         0.408424       105751.03  304768.73  Rangpur  108733.99
24         0.465947        99281.34  140574.81    Dhaka  108552.04
25         0.391080       139553.16  137962.62      Ctg  107404.34
26         0.455574       144135.98  134050.07  Rangpur  105733.54
27         0.436093       127864.55  353183.81    Dhaka  105008.31
28         0.399467       182645.56  118148.20  Rangpur  103282.38
29         0.396769       153032.06  107138.38    Dhaka  101004.64
30         0.374931       115641.28   91131.24  Rangpur   99937.59
31         0.369741       152701.92   88218.23    Dhaka   97483.56
32         0.383485       129219.61   46085.25      Ctg   97427.84
33         0.335617       103057.49  214634.81  Rangpur   96778.92
34         0.280776       157693.92  210797.67      Ctg   96712.80
35         0.278284        85047.44  205517.64    Dhaka   96479.51
36         0.173353       127056.21  201126.82  Rangpur   90708.19
37         0.266527        51283.14  197029.42      Ctg   89949.14
38         0.122345        65947.93  185265.10    Dhaka   81229.06
39         0.233194        82982.09  174999.30      Ctg   81005.76
40         0.173901       118546.05  172795.67      Ctg   78239.91
41         0.168691        84710.77  164470.71  Rangpur   77798.83
42         0.142976        96189.63  148001.11      Ctg   71498.49
43         0.093776       127382.30   35534.17    Dhaka   69758.98
44         0.134127       154806.14   28334.72      Ctg   65200.33
45         0.006049       124153.04    1903.93    Dhaka   64926.08
46         0.007956       115816.21  297114.46  Rangpur   49490.75
47         0.000000       135426.92       0.00      Ctg   42559.73
48         0.003278        51743.15       0.00    Dhaka   35673.41
49         0.000000       116983.80   45173.06      Ctg   14681.40

In [13]:
df['Administration']=scaler.fit_transform(df[['Administration']])

In [14]:
df

    Marketing Spend  Administration  Transport     Area     Profit
0          0.692617        0.651744  471784.10    Dhaka  192261.83
1          0.983359        0.761972  443898.53      Ctg  191792.06
2          0.927985        0.379579  407934.54  Rangpur  191050.39
3          0.873136        0.512998  383199.62    Dhaka  182901.99
4          0.859438        0.305328  366168.42  Rangpur  166187.94
5          0.797566        0.369448  362861.36    Dhaka  156991.12
6          0.814128        0.730161  127716.82      Ctg  156122.51
7          0.788018        0.717457  323876.68  Rangpur  155752.60
8          0.729018        0.741733  311613.29    Dhaka  152211.77
9          0.745906        0.436929  304981.62      Ctg  149759.96
10         0.616351        0.451506  229160.95  Rangpur  146121.95
11         0.608845        0.308364  249744.55      Ctg  144259.40
12         0.567670        0.578836  249839.44  Rangpur  141585.52
13         0.556352        0.641066  252664.93      Ctg  134307.35
14         0.725394        0.801327  256512.92  Rangpur  132602.65
15         1.000000        0.543030  261776.23    Dhaka  129917.04
16         0.471808        0.535270  264346.06      Ctg  126992.93
17         0.572468        0.714013  282574.31    Dhaka  125370.37
18         0.554881        0.478772  294919.57  Rangpur  124266.90
19         0.522650        0.778236        NaN    Dhaka  122776.86
20         0.461169        0.476424  298664.47      Ctg  118474.03
21         0.474084        0.780210  299737.29    Dhaka  111313.02
22         0.447505        0.544293  303319.26  Rangpur  110352.25
23         0.408424        0.414638  304768.73  Rangpur  108733.99
24         0.465947        0.365388  140574.81    Dhaka  108552.04
25         0.391080        0.671958  137962.62      Ctg  107404.34
26         0.455574        0.706845  134050.07  Rangpur  105733.54
27         0.436093        0.582978  353183.81    Dhaka  105008.31
28         0.399467        1.000000  118148.20  Rangpur  103282.38
29         0.396769        0.774566  107138.38    Dhaka  101004.64
30         0.374931        0.489928   91131.24  Rangpur   99937.59
31         0.369741        0.772053   88218.23    Dhaka   97483.56
32         0.383485        0.593294   46085.25      Ctg   97427.84
33         0.335617        0.394134  214634.81  Rangpur   96778.92
34         0.280776        0.810055  210797.67      Ctg   96712.80
35         0.278284        0.257032  205517.64    Dhaka   96479.51
36         0.173353        0.576825  201126.82  Rangpur   90708.19
37         0.266527        0.000000  197029.42      Ctg   89949.14
38         0.122345        0.111636  185265.10    Dhaka   81229.06
39         0.233194        0.241309  174999.30      Ctg   81005.76
40         0.173901        0.512041  172795.67      Ctg   78239.91
41         0.168691        0.254469  164470.71  Rangpur   77798.83
42         0.142976        0.341852  148001.11      Ctg   71498.49
43         0.093776        0.579307   35534.17    Dhaka   69758.98
44         0.134127        0.788072   28334.72      Ctg   65200.33
45         0.006049        0.554724    1903.93    Dhaka   64926.08
46         0.007956        0.491260  297114.46  Rangpur   49490.75
47         0.000000        0.640547       0.00      Ctg   42559.73
48         0.003278        0.003502       0.00    Dhaka   35673.41
49         0.000000        0.500148   45173.06      Ctg   14681.40

#  Standardization

In [15]:
from sklearn.preprocessing import StandardScaler

In [16]:
df=pd.read_csv('agora.csv')

In [17]:
scaler=StandardScaler()

In [18]:
df['Marketing Spend']=scaler.fit_transform(df[['Marketing Spend']])

In [19]:
df

    Marketing Spend  Administration  Transport     Area     Profit
0          0.897913       136897.80  471784.10    Dhaka  192261.83
1          1.955860       151377.59  443898.53      Ctg  191792.06
2          1.754364       101145.55  407934.54  Rangpur  191050.39
3          1.554784       118671.85  383199.62    Dhaka  182901.99
4          1.504937        91391.77  366168.42  Rangpur  166187.94
5          1.279800        99814.71  362861.36    Dhaka  156991.12
6          1.340066       147198.87  127716.82      Ctg  156122.51
7          1.245057       145530.06  323876.68  Rangpur  155752.60
8          1.030369       148718.95  311613.29    Dhaka  152211.77
9          1.091819       108679.17  304981.62      Ctg  149759.96
10         0.620398       110594.11  229160.95  Rangpur  146121.95
11         0.593085        91790.61  249744.55      Ctg  144259.40
12         0.443260       127320.38  249839.44  Rangpur  141585.52
13         0.402078       135495.07  252664.93      Ctg  134307.35
14         1.017181       156547.42  256512.92  Rangpur  132602.65
15         2.016411       122616.84  261776.23    Dhaka  129917.04
16         0.094441       121597.55  264346.06      Ctg  126992.93
17         0.460720       145077.58  282574.31    Dhaka  125370.37
18         0.396725       114175.79  294919.57  Rangpur  124266.90
19         0.279442       153514.11        NaN    Dhaka  122776.86
20         0.055726       113867.30  298664.47      Ctg  118474.03
21         0.102724       153773.43  299737.29    Dhaka  111313.02
22         0.006007       122782.75  303319.26  Rangpur  110352.25
23        -0.136201       105751.03  304768.73  Rangpur  108733.99
24         0.073115        99281.34  140574.81    Dhaka  108552.04
25        -0.199312       139553.16  137962.62      Ctg  107404.34
26         0.035370       144135.98  134050.07  Rangpur  105733.54
27        -0.035519       127864.55  353183.81    Dhaka  105008.31
28        -0.168793       182645.56  118148.20  Rangpur  103282.38
29        -0.178609       153032.06  107138.38    Dhaka  101004.64
30        -0.258074       115641.28   91131.24  Rangpur   99937.59
31        -0.276958       152701.92   88218.23    Dhaka   97483.56
32        -0.226949       129219.61   46085.25      Ctg   97427.84
33        -0.401129       103057.49  214634.81  Rangpur   96778.92
34        -0.600682       157693.92  210797.67      Ctg   96712.80
35        -0.609750        85047.44  205517.64    Dhaka   96479.51
36        -0.991570       127056.21  201126.82  Rangpur   90708.19
37        -0.652532        51283.14  197029.42      Ctg   89949.14
38        -1.177178        65947.93  185265.10    Dhaka   81229.06
39        -0.773820        82982.09  174999.30      Ctg   81005.76
40        -0.989577       118546.05  172795.67      Ctg   78239.91
41        -1.008534        84710.77  164470.71  Rangpur   77798.83
42        -1.102106        96189.63  148001.11      Ctg   71498.49
43        -1.281134       127382.30   35534.17    Dhaka   69758.98
44        -1.134305       154806.14   28334.72      Ctg   65200.33
45        -1.600350       124153.04    1903.93    Dhaka   64926.08
46        -1.593413       115816.21  297114.46  Rangpur   49490.75
47        -1.622362       135426.92       0.00      Ctg   42559.73
48        -1.610433        51743.15       0.00    Dhaka   35673.41
49        -1.622362       116983.80   45173.06      Ctg   14681.40

# Max Absolute Scaler

In [21]:
absolute= df['Administration'].abs()

In [22]:
absolute

0     136897.80
1     151377.59
2     101145.55
3     118671.85
4      91391.77
5      99814.71
6     147198.87
7     145530.06
8     148718.95
9     108679.17
10    110594.11
11     91790.61
12    127320.38
13    135495.07
14    156547.42
15    122616.84
16    121597.55
17    145077.58
18    114175.79
19    153514.11
20    113867.30
21    153773.43
22    122782.75
23    105751.03
24     99281.34
25    139553.16
26    144135.98
27    127864.55
28    182645.56
29    153032.06
30    115641.28
31    152701.92
32    129219.61
33    103057.49
34    157693.92
35     85047.44
36    127056.21
37     51283.14
38     65947.93
39     82982.09
40    118546.05
41     84710.77
42     96189.63
43    127382.30
44    154806.14
45    124153.04
46    115816.21
47    135426.92
48     51743.15
49    116983.80
Name: Administration, dtype: float64

In [25]:
absolute.max()

182645.56

In [26]:
df['Administration']/absolute.max()

0     0.749527
1     0.828805
2     0.553781
3     0.649738
4     0.500378
5     0.546494
6     0.805926
7     0.796789
8     0.814249
9     0.595028
10    0.605512
11    0.502561
12    0.697090
13    0.741847
14    0.857110
15    0.671338
16    0.665757
17    0.794312
18    0.625122
19    0.840503
20    0.623433
21    0.841923
22    0.672246
23    0.578996
24    0.543574
25    0.764065
26    0.789157
27    0.700069
28    1.000000
29    0.837864
30    0.633146
31    0.836056
32    0.707488
33    0.564249
34    0.863388
35    0.465642
36    0.695644
37    0.280780
38    0.361071
39    0.454334
40    0.649050
41    0.463799
42    0.526646
43    0.697429
44    0.847577
45    0.679748
46    0.634104
47    0.741474
48    0.283298
49    0.640496
Name: Administration, dtype: float64

# Robust Scaler

In [27]:
from sklearn.preprocessing import RobustScaler

In [28]:
robust=RobustScaler()

In [30]:
df['Transport']=robust.fit_transform(df[['Transport']])

In [31]:
df

    Marketing Spend  Administration  Transport     Area     Profit
0          0.897913       136897.80   1.552016    Dhaka  192261.83
1          1.955860       151377.59   1.383714      Ctg  191792.06
2          1.754364       101145.55   1.166654  Rangpur  191050.39
3          1.554784       118671.85   1.017368    Dhaka  182901.99
4          1.504937        91391.77   0.914576  Rangpur  166187.94
5          1.279800        99814.71   0.894617    Dhaka  156991.12
6          1.340066       147198.87  -0.524591      Ctg  156122.51
7          1.245057       145530.06   0.659326  Rangpur  155752.60
8          1.030369       148718.95   0.585311    Dhaka  152211.77
9          1.091819       108679.17   0.545285      Ctg  149759.96
10         0.620398       110594.11   0.087672  Rangpur  146121.95
11         0.593085        91790.61   0.211904      Ctg  144259.40
12         0.443260       127320.38   0.212476  Rangpur  141585.52
13         0.402078       135495.07   0.229530      Ctg  134307.35
14         1.017181       156547.42   0.252754  Rangpur  132602.65
15         2.016411       122616.84   0.284521    Dhaka  129917.04
16         0.094441       121597.55   0.300031      Ctg  126992.93
17         0.460720       145077.58   0.410047    Dhaka  125370.37
18         0.396725       114175.79   0.484556  Rangpur  124266.90
19         0.279442       153514.11        NaN    Dhaka  122776.86
20         0.055726       113867.30   0.507158      Ctg  118474.03
21         0.102724       153773.43   0.513633    Dhaka  111313.02
22         0.006007       122782.75   0.535252  Rangpur  110352.25
23        -0.136201       105751.03   0.544000  Rangpur  108733.99
24         0.073115        99281.34  -0.446987    Dhaka  108552.04
25        -0.199312       139553.16  -0.462753      Ctg  107404.34
26         0.035370       144135.98  -0.486367  Rangpur  105733.54
27        -0.035519       127864.55   0.836208    Dhaka  105008.31
28        -0.168793       182645.56  -0.582342  Rangpur  103282.38
29        -0.178609       153032.06  -0.648791    Dhaka  101004.64
30        -0.258074       115641.28  -0.745402  Rangpur   99937.59
31        -0.276958       152701.92  -0.762983    Dhaka   97483.56
32        -0.226949       129219.61  -1.017276      Ctg   97427.84
33        -0.401129       103057.49   0.000000  Rangpur   96778.92
34        -0.600682       157693.92  -0.023159      Ctg   96712.80
35        -0.609750        85047.44  -0.055026    Dhaka   96479.51
36        -0.991570       127056.21  -0.081527  Rangpur   90708.19
37        -0.652532        51283.14  -0.106257      Ctg   89949.14
38        -1.177178        65947.93  -0.177260    Dhaka   81229.06
39        -0.773820        82982.09  -0.239219      Ctg   81005.76
40        -0.989577       118546.05  -0.252519      Ctg   78239.91
41        -1.008534        84710.77  -0.302764  Rangpur   77798.83
42        -1.102106        96189.63  -0.402166      Ctg   71498.49
43        -1.281134       127382.30  -1.080956    Dhaka   69758.98
44        -1.134305       154806.14  -1.124408      Ctg   65200.33
45        -1.600350       124153.04  -1.283931    Dhaka   64926.08
46        -1.593413       115816.21   0.497803  Rangpur   49490.75
47        -1.622362       135426.92  -1.295422      Ctg   42559.73
48        -1.610433        51743.15  -1.295422    Dhaka   35673.41
49        -1.622362       116983.80  -1.022781      Ctg   14681.40